"""
Evaluate TargetTrace3 on an external dataset.

Expected CSV columns
--------------------
  smiles           (str)   canonical SMILES
  protein_sequence (str)   full amino-acid sequence (single-letter)
  active           (0/1)   binding label
  pic50            (float) optional; leave blank / NaN for inactives

Negative pairs
--------------
  If active=0 rows exist in the CSV they are used directly.
  If all rows are positive, negatives are generated by shuffling proteins
  within each batch (same protocol as training / benchmark).

Usage
-----
  python evaluate_external.py path/to/dataset.csv
  python evaluate_external.py path/to/dataset.csv --batch_size 256 --label BindingDB
"""
import argparse
import gc
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from torch.amp import autocast
from torch.utils.data import DataLoader, Dataset

from embedders import (ESM_DIM, _PROT_POOLED, _load, _seq_key,
                       embed_proteins, load_residues_subset, unload_models)
from features import FP_DIM, mol_fp, precompute_fps
from trainer import (USE_AMP, _bedroc, _collate, _ef, device,
                     load_latest, TargetTrace3Dataset)

try:
    from scipy.stats import pearsonr as _pearsonr, spearmanr as _spearmanr
    from sklearn.metrics import (
        average_precision_score, precision_recall_curve,
        roc_auc_score, roc_curve,
    )
    _SKLEARN_OK = True
except ImportError:
    _SKLEARN_OK = False


# ── Dataset ────────────────────────────────────────────────────────────────

class _ExternalDataset(Dataset):
    """
    Wraps external (smiles, seq_key, pic50_norm) triples.
    Returns (fp, esm_pooled, prot_idx, pic50_norm).
    """
    def __init__(self, df: pd.DataFrame, p_mean: float, p_std: float,
                 fp_cache: dict, prot_pool: dict,
                 prot_key_to_idx: dict):

        self._fp:   dict[str, np.ndarray] = {}
        self._prot: dict[str, np.ndarray] = {}

        _zero = np.zeros(ESM_DIM, dtype=np.float32)

        for smi in df["smiles"].unique():
            fp = fp_cache.get(str(smi))
            if fp is not None:
                self._fp[str(smi)] = fp

        for key in prot_key_to_idx:
            self._prot[key] = prot_pool.get(key, _zero.copy()).astype(np.float32)

        valid_smi  = set(self._fp.keys())
        valid_keys = set(prot_key_to_idx.keys())
        df2 = df[df["smiles"].isin(valid_smi) &
                 df["seq_key"].isin(valid_keys)].copy()

        df2["prot_idx"] = df2["seq_key"].map(prot_key_to_idx)
        df2["pic50_n"]  = (pd.to_numeric(df2.get("pic50", np.nan), errors="coerce")
                           .sub(p_mean).div(p_std))

        self._smiles_arr   = df2["smiles"].tolist()
        self._prot_key_arr = df2["seq_key"].tolist()
        self._prot_idx_arr = df2["prot_idx"].to_numpy(dtype=np.int32)
        self._pic50_arr    = df2["pic50_n"].to_numpy(dtype=np.float32)

    def __len__(self):
        return len(self._smiles_arr)

    def __getitem__(self, idx):
        smi = self._smiles_arr[idx]
        key = self._prot_key_arr[idx]
        return (
            torch.tensor(self._fp[smi],     dtype=torch.float32),
            torch.tensor(self._prot[key],   dtype=torch.float32),
            int(self._prot_idx_arr[idx]),
            float(self._pic50_arr[idx]),
        )


# ── Core evaluation ────────────────────────────────────────────────────────

def evaluate(
    csv_path: str | Path,
    label:      str = "External",
    batch_size: int = 256,
    status_cb=None,
) -> dict:
    """
    Load csv_path, run TargetTrace3, return metrics dict.

    Returned keys: AUC, AUPRC, EF1%, EF5%, BEDROC, MAE, RMSE,
                   Spearman, Pearson, n_pos, n_neg, label
    """
    def _st(msg):
        if status_cb:
            status_cb(msg)
        else:
            print(msg)

    if not _SKLEARN_OK:
        raise RuntimeError("sklearn and scipy are required for evaluation.")

    # ── 1. Load model ──────────────────────────────────────────────────────
    _st(f"[{label}] Loading model…")
    model, _, _, _, norm_stats = load_latest()
    if model is None:
        raise RuntimeError("No trained model found. Run training first.")
    p_mean = norm_stats.get("pic50_mean", 7.0)
    p_std  = norm_stats.get("pic50_std",  1.5)
    model.eval()

    # ── 2. Load and validate CSV ───────────────────────────────────────────
    _st(f"[{label}] Reading {csv_path}…")
    df = pd.read_csv(csv_path)
    required = {"smiles", "protein_sequence", "active"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"CSV is missing required columns: {missing}")

    df = df[df["smiles"].notna() & df["protein_sequence"].notna()].copy()
    df["active"] = pd.to_numeric(df["active"], errors="coerce").fillna(0).astype(int)
    df["seq_key"] = df["protein_sequence"].astype(str).map(_seq_key)
    if "pic50" not in df.columns:
        df["pic50"] = np.nan
    df["pic50"] = pd.to_numeric(df["pic50"], errors="coerce")

    pos_df = df[df["active"] == 1].reset_index(drop=True)
    neg_df = df[df["active"] == 0].reset_index(drop=True)
    has_explicit_neg = len(neg_df) > 0
    _use_shuffle_neg = not has_explicit_neg

    _st(f"[{label}] {len(pos_df):,} positives, "
        f"{len(neg_df):,} explicit negatives "
        f"({'shuffle negatives will be generated' if _use_shuffle_neg else 'using explicit negatives'})")

    if len(pos_df) < 2:
        raise ValueError("Need at least 2 positive pairs for evaluation.")

    # ── 3. Compute / load feature caches ──────────────────────────────────
    _st(f"[{label}] Computing fingerprints…")
    all_smiles = df["smiles"].unique().tolist()
    precompute_fps(all_smiles, status_cb=status_cb)

    _st(f"[{label}] Computing ESM-2 embeddings…")
    all_seqs = df["protein_sequence"].unique().tolist()
    embed_proteins(all_seqs, status_cb=status_cb)
    unload_models()

    _st(f"[{label}] Loading caches…")
    from features import load_fp_subset
    fp_cache = load_fp_subset(set(str(s) for s in all_smiles))
    prot_pool = _load(_PROT_POOLED)

    unique_keys    = df["seq_key"].unique().tolist()
    prot_key_to_idx = {k: i for i, k in enumerate(unique_keys)}
    residue_cache  = load_residues_subset(set(unique_keys), status_cb=status_cb)

    # ── 4. Build residue tensor ────────────────────────────────────────────
    max_L       = max((r.shape[0] for r in residue_cache.values()), default=1)
    N_prot      = len(unique_keys)
    prot_res_t  = torch.zeros(N_prot, max_L, ESM_DIM, device=device, dtype=torch.float32)
    prot_mask_t = torch.ones( N_prot, max_L,           device=device, dtype=torch.bool)
    for k, i in prot_key_to_idx.items():
        r = residue_cache.get(k)
        if r is not None:
            L = r.shape[0]
            prot_res_t[i, :L]  = torch.tensor(r, dtype=torch.float32)
            prot_mask_t[i, :L] = False
    del residue_cache
    gc.collect()

    # ── 5. Build dataset and DataLoader ───────────────────────────────────
    _st(f"[{label}] Building dataset…")
    pos_ds = _ExternalDataset(pos_df, p_mean, p_std, fp_cache, prot_pool, prot_key_to_idx)
    pos_loader = DataLoader(pos_ds, batch_size=batch_size, shuffle=False,
                            collate_fn=_collate, num_workers=0,
                            pin_memory=(device.type == "cuda"))

    if has_explicit_neg:
        neg_ds = _ExternalDataset(neg_df, p_mean, p_std, fp_cache, prot_pool, prot_key_to_idx)
        neg_loader = DataLoader(neg_ds, batch_size=batch_size, shuffle=False,
                                collate_fn=_collate, num_workers=0,
                                pin_memory=(device.type == "cuda"))

    del fp_cache, prot_pool
    gc.collect()
    _st(f"[{label}] {len(pos_ds):,} valid positives loaded.")

    # ── 6. Run inference ───────────────────────────────────────────────────
    _st(f"[{label}] Running model inference…")
    y_true, y_score, pt, pp = [], [], [], []

    if _use_shuffle_neg:
        # Generate negatives by shuffling proteins within each batch
        with torch.no_grad():
            for fp, esm_p, prot_idx, pic50s in pos_loader:
                fp, esm_p, prot_idx, pic50s = [b.to(device, non_blocking=True)
                                                for b in [fp, esm_p, prot_idx, pic50s]]
                B = len(fp)
                pos_res  = prot_res_t[prot_idx]
                pos_mask = prot_mask_t[prot_idx]

                neg_perm = torch.randperm(B, device=device)
                same     = neg_perm == torch.arange(B, device=device)
                neg_perm[same] = (neg_perm[same] + 1) % B
                neg_res  = prot_res_t[prot_idx[neg_perm]]
                neg_mask = prot_mask_t[prot_idx[neg_perm]]

                with autocast(device_type="cuda", enabled=USE_AMP):
                    act_pos, p50_pos = model(fp, esm_p, pos_res, pos_mask)
                    act_neg, _       = model(fp, esm_p, neg_res, neg_mask)

                y_true.extend([1] * B + [0] * B)
                y_score.extend(torch.sigmoid(act_pos).cpu().float().tolist())
                y_score.extend(torch.sigmoid(act_neg).cpu().float().tolist())

                for t, p in zip(pic50s.cpu().numpy(),
                                p50_pos.cpu().float().numpy()):
                    if not np.isnan(float(t)):
                        pt.append(float(t) * p_std + p_mean)
                        pp.append(float(p) * p_std + p_mean)

    else:
        # Score positives
        with torch.no_grad():
            for fp, esm_p, prot_idx, pic50s in pos_loader:
                fp, esm_p, prot_idx, pic50s = [b.to(device, non_blocking=True)
                                                for b in [fp, esm_p, prot_idx, pic50s]]
                pos_res  = prot_res_t[prot_idx]
                pos_mask = prot_mask_t[prot_idx]
                with autocast(device_type="cuda", enabled=USE_AMP):
                    act_pos, p50_pos = model(fp, esm_p, pos_res, pos_mask)
                B = len(fp)
                y_true.extend([1] * B)
                y_score.extend(torch.sigmoid(act_pos).cpu().float().tolist())
                for t, p in zip(pic50s.cpu().numpy(),
                                p50_pos.cpu().float().numpy()):
                    if not np.isnan(float(t)):
                        pt.append(float(t) * p_std + p_mean)
                        pp.append(float(p) * p_std + p_mean)

        # Score explicit negatives
        with torch.no_grad():
            for fp, esm_p, prot_idx, _ in neg_loader:
                fp, esm_p, prot_idx = [b.to(device, non_blocking=True)
                                        for b in [fp, esm_p, prot_idx]]
                neg_res  = prot_res_t[prot_idx]
                neg_mask = prot_mask_t[prot_idx]
                with autocast(device_type="cuda", enabled=USE_AMP):
                    act_neg, _ = model(fp, esm_p, neg_res, neg_mask)
                B = len(fp)
                y_true.extend([0] * B)
                y_score.extend(torch.sigmoid(act_neg).cpu().float().tolist())

    # ── 7. Compute metrics ─────────────────────────────────────────────────
    y_true_a  = np.array(y_true)
    y_score_a = np.array(y_score)

    auc   = roc_auc_score(y_true_a, y_score_a)
    auprc = average_precision_score(y_true_a, y_score_a)
    ef1   = _ef(y_true_a, y_score_a, 0.01)
    ef5   = _ef(y_true_a, y_score_a, 0.05)
    bedr  = _bedroc(y_true_a, y_score_a)

    mae = rmse = spear = pear = 0.0
    if len(pt) >= 2:
        pt_a = np.array(pt, dtype=np.float32)
        pp_a = np.array(pp, dtype=np.float32)
        mae  = float(np.mean(np.abs(pt_a - pp_a)))
        rmse = float(np.sqrt(np.mean((pt_a - pp_a) ** 2)))
        sr   = _spearmanr(pt_a, pp_a)
        pr_  = _pearsonr(pt_a, pp_a)
        spear = float(getattr(sr,  "statistic", getattr(sr,  "correlation", 0.0)))
        pear  = float(getattr(pr_, "statistic", pr_[0] if isinstance(pr_, tuple) else 0.0))

    metrics = {
        "label":    label,
        "n_pos":    int(y_true_a.sum()),
        "n_neg":    int((1 - y_true_a).sum()),
        "AUC":      round(auc,   4),
        "AUPRC":    round(auprc, 4),
        "EF1%":     round(ef1,   2),
        "EF5%":     round(ef5,   2),
        "BEDROC":   round(bedr,  4),
        "MAE":      round(mae,   4),
        "RMSE":     round(rmse,  4),
        "Spearman": round(spear, 4),
        "Pearson":  round(pear,  4),
    }

    _st(f"\n{'─'*55}")
    _st(f"  External evaluation: {label}")
    _st(f"{'─'*55}")
    for k, v in metrics.items():
        if k not in ("label",):
            _st(f"  {k:<12} {v}")
    _st(f"{'─'*55}\n")

    return metrics


# ── CLI ────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("csv",         help="Path to evaluation CSV")
    ap.add_argument("--label",     default="External", help="Label for results")
    ap.add_argument("--batch_size",type=int, default=256)
    args = ap.parse_args()

    evaluate(args.csv, label=args.label, batch_size=args.batch_size)
